/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculatorapp;



/**
 *
 * @author jimstewart
 */
public class CalculatorApp extends javax.swing.JFrame {
    Operation activeOperation;
    boolean overWrite = true;
    double firstNumber;
    enum Operation{
        ADD,
        SUBTRACT,
        MULTIPLY,
        DIVIDE,
        NONE
    }


    /**
     * Creates new form UI
     */
    public CalculatorApp() {
        initComponents();
        activeOperation = Operation.NONE;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayField = new javax.swing.JTextField();
        sevenButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        oneButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        decimalButton = new javax.swing.JButton();
        equalsButton = new javax.swing.JButton();
        plusButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        timesButton = new javax.swing.JButton();
        divideButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sevenButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        sevenButton.setText("7");
        sevenButton.setToolTipText("");
        sevenButton.setPreferredSize(new java.awt.Dimension(40, 40));
        sevenButton.setSize(new java.awt.Dimension(40, 40));
        sevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenButtonActionPerformed(evt);
            }
        });

        eightButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        eightButton.setText("8");
        eightButton.setToolTipText("");
        eightButton.setPreferredSize(new java.awt.Dimension(40, 40));
        eightButton.setSize(new java.awt.Dimension(40, 40));
        eightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightButtonActionPerformed(evt);
            }
        });

        nineButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        nineButton.setText("9");
        nineButton.setToolTipText("");
        nineButton.setPreferredSize(new java.awt.Dimension(40, 40));
        nineButton.setSize(new java.awt.Dimension(40, 40));
        nineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineButtonActionPerformed(evt);
            }
        });

        fourButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        fourButton.setText("4");
        fourButton.setToolTipText("");
        fourButton.setPreferredSize(new java.awt.Dimension(40, 40));
        fourButton.setSize(new java.awt.Dimension(40, 40));
        fourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourButtonActionPerformed(evt);
            }
        });

        oneButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        oneButton.setText("1");
        oneButton.setToolTipText("");
        oneButton.setPreferredSize(new java.awt.Dimension(40, 40));
        oneButton.setSize(new java.awt.Dimension(40, 40));
        oneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneButtonActionPerformed(evt);
            }
        });

        fiveButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        fiveButton.setText("5");
        fiveButton.setToolTipText("");
        fiveButton.setPreferredSize(new java.awt.Dimension(40, 40));
        fiveButton.setSize(new java.awt.Dimension(40, 40));
        fiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveButtonActionPerformed(evt);
            }
        });

        twoButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        twoButton.setText("2");
        twoButton.setToolTipText("");
        twoButton.setPreferredSize(new java.awt.Dimension(40, 40));
        twoButton.setSize(new java.awt.Dimension(40, 40));
        twoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoButtonActionPerformed(evt);
            }
        });

        sixButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        sixButton.setText("6");
        sixButton.setToolTipText("");
        sixButton.setPreferredSize(new java.awt.Dimension(40, 40));
        sixButton.setSize(new java.awt.Dimension(40, 40));
        sixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixButtonActionPerformed(evt);
            }
        });

        threeButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        threeButton.setText("3");
        threeButton.setToolTipText("");
        threeButton.setPreferredSize(new java.awt.Dimension(40, 40));
        threeButton.setSize(new java.awt.Dimension(40, 40));
        threeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeButtonActionPerformed(evt);
            }
        });

        zeroButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        zeroButton.setText("0");
        zeroButton.setToolTipText("");
        zeroButton.setPreferredSize(new java.awt.Dimension(40, 40));
        zeroButton.setSize(new java.awt.Dimension(40, 40));
        zeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonActionPerformed(evt);
            }
        });

        decimalButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        decimalButton.setText(".");
        decimalButton.setToolTipText("");
        decimalButton.setPreferredSize(new java.awt.Dimension(40, 40));
        decimalButton.setSize(new java.awt.Dimension(40, 40));
        decimalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalButtonActionPerformed(evt);
            }
        });

        equalsButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        equalsButton.setText("=");
        equalsButton.setToolTipText("");
        equalsButton.setPreferredSize(new java.awt.Dimension(40, 40));
        equalsButton.setSize(new java.awt.Dimension(40, 40));
        equalsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsButtonActionPerformed(evt);
            }
        });

        plusButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        plusButton.setText("+");
        plusButton.setToolTipText("");
        plusButton.setPreferredSize(new java.awt.Dimension(40, 40));
        plusButton.setSize(new java.awt.Dimension(40, 40));
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });

        minusButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        minusButton.setText("-");
        minusButton.setToolTipText("");
        minusButton.setPreferredSize(new java.awt.Dimension(40, 40));
        minusButton.setSize(new java.awt.Dimension(40, 40));
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });

        timesButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        timesButton.setText("x");
        timesButton.setToolTipText("");
        timesButton.setPreferredSize(new java.awt.Dimension(40, 40));
        timesButton.setSize(new java.awt.Dimension(40, 40));
        timesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timesButtonActionPerformed(evt);
            }
        });

        divideButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        divideButton.setText("/");
        divideButton.setToolTipText("");
        divideButton.setPreferredSize(new java.awt.Dimension(40, 40));
        divideButton.setSize(new java.awt.Dimension(40, 40));
        divideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        clearButton.setText("Clear");
        clearButton.setToolTipText("");
        clearButton.setPreferredSize(new java.awt.Dimension(105, 40));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(displayField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(timesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(decimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(equalsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(divideButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equalsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divideButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * if overWrite = true replaces button with button number & turns off overWrite
 * otherwise appends number to button text
 * 
 * @param evt 
 */
    private void zeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroButtonActionPerformed
        
        addDigit(0);
    }//GEN-LAST:event_zeroButtonActionPerformed
/**
 * if overWrite = true replaces button with button number & turns off overWrite
 * otherwise appends number to button text
 * 
 * @param evt 
 */

    private void oneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneButtonActionPerformed
        addDigit(1);
    }//GEN-LAST:event_oneButtonActionPerformed

/**
 * if overWrite = true replaces button with button number & turns off overWrite
 * otherwise appends number to button text
 * 
 * @param evt 
 */
    private void twoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoButtonActionPerformed
        addDigit(2);
    }//GEN-LAST:event_twoButtonActionPerformed

/**
 * if overWrite = true replaces button with button number & turns off overWrite
 * otherwise appends number to button text
 * 
 * @param evt 
 */
    private void threeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeButtonActionPerformed
        addDigit(3);
    }//GEN-LAST:event_threeButtonActionPerformed

/**
 * if overWrite = true replaces button with button number & turns off overWrite
 * otherwise appends number to button text
 * 
 * @param evt 
 */
    private void fourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourButtonActionPerformed
        addDigit(4);
    }//GEN-LAST:event_fourButtonActionPerformed

/**
 * if overWrite = true replaces button with button number & turns off overWrite
 * otherwise appends number to button text
 * 
 * @param evt 
 */
    private void fiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveButtonActionPerformed
        addDigit(5);
    }//GEN-LAST:event_fiveButtonActionPerformed

/**
 * if overWrite = true replaces button with button number & turns off overWrite
 * otherwise appends number to button text
 * 
 * @param evt 
 */
    private void sixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixButtonActionPerformed
        addDigit(6);
    }//GEN-LAST:event_sixButtonActionPerformed

/**
 * if overWrite = true replaces button with button number & turns off overWrite
 * otherwise appends number to button text
 * 
 * @param evt 
 */
    private void sevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenButtonActionPerformed
        addDigit(7);
    }//GEN-LAST:event_sevenButtonActionPerformed

/**
 * if overWrite = true replaces button with button number & turns off overWrite
 * otherwise appends number to button text
 * 
 * @param evt 
 */
    private void eightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightButtonActionPerformed
        addDigit(8);
    }//GEN-LAST:event_eightButtonActionPerformed

/**
 * if overWrite = true replaces button with button number & turns off overWrite
 * otherwise appends number to button text
 * 
 * @param evt 
 */
    private void nineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineButtonActionPerformed
        addDigit(9);
    }//GEN-LAST:event_nineButtonActionPerformed

/**
 * Clear what's in the display, and reset operation to nothing and overwrite to true
 * 
 * @param evt 
 */
    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        //Clear button team, insert code here
    }//GEN-LAST:event_clearButtonActionPerformed


    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        setOperation(Operation.ADD);
    }//GEN-LAST:event_plusButtonActionPerformed


    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        setOperation(Operation.SUBTRACT);
    }//GEN-LAST:event_minusButtonActionPerformed


    private void timesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timesButtonActionPerformed
        setOperation(Operation.MULTIPLY);
    }//GEN-LAST:event_timesButtonActionPerformed


    private void divideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideButtonActionPerformed
        setOperation(Operation.DIVIDE);
    }//GEN-LAST:event_divideButtonActionPerformed

/**
 * If there is an active operation
 *    - perform that operation with firstNumber
 *    - replace displayField with overWrite
 *    - turn overWrite to true
 * If there is no active operation, do nothing
 * 
 * @param evt 
 */
    private void equalsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsButtonActionPerformed
        //Equals button team insert code here
    }//GEN-LAST:event_equalsButtonActionPerformed

/**
 * if overWrite = true 
 *    - replaces button with zero followed by decimal point
 *    - turns off overWrite
 * otherwise 
 *    - if the number in displayField does not contain a decimal already add a decimal
 *    - else do nothing
 * 
 * @param evt 
 */
    private void decimalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalButtonActionPerformed
        //Decimal button team insert code here
    }//GEN-LAST:event_decimalButtonActionPerformed

    /**
     * if overWrite = true replaces button with button number & turns off overWrite
     * otherwise appends number to button text
     * @param n 
     */    
    private void addDigit(int n){
        String digitString = Integer.toString(n);
        if(overWrite){
            displayField.setText(digitString);
            overWrite = false;
            }
        else
            displayField.setText(displayField.getText() + digitString);
    }
    
    /** set activeOperation to the operation o
     * 
     * @param o 
     */
    private void setOperation(Operation o){
        //Operation button team set code here
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorApp().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton clearButton;
    protected javax.swing.JButton decimalButton;
    protected javax.swing.JTextField displayField;
    protected javax.swing.JButton divideButton;
    protected javax.swing.JButton eightButton;
    protected javax.swing.JButton equalsButton;
    protected javax.swing.JButton fiveButton;
    protected javax.swing.JButton fourButton;
    protected javax.swing.JButton minusButton;
    protected javax.swing.JButton nineButton;
    protected javax.swing.JButton oneButton;
    protected javax.swing.JButton plusButton;
    protected javax.swing.JButton sevenButton;
    protected javax.swing.JButton sixButton;
    protected javax.swing.JButton threeButton;
    protected javax.swing.JButton timesButton;
    protected javax.swing.JButton twoButton;
    protected javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables
}
